# mkdocs.yml - Configuration for MkDocs

site_name: Go Optimization Guide
site_description: Patterns and Techniques for Writing High-Performance Applications with Go
repo_url: https://github.com/astavonin/go-optimization-guide
site_url: https://goperf.dev

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  icon:
    annotation: material/plus-circle
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - toc.follow
    - navigation.sections
    - navigation.tabs
    - toc.integrate

extra:
  social:
    - icon: fontawesome/solid/square-rss
      link: https://goperf.dev/feed_rss_created.xml
    - icon: fontawesome/brands/github
      link: https://github.com/astavonin/go-optimization-guide
  analytics:
    provider: google
    property: G-9G75PKHPKN

nav:
  - Home: index.md
  - Blog: blog/index.md
  - Common Performance Patterns:
    - 01-common-patterns/index.md
    - Memory Management & Efficiency:
      - Object Pooling: 01-common-patterns/object-pooling.md
      - Memory Preallocation: 01-common-patterns/mem-prealloc.md
      - Struct Field Alignment: 01-common-patterns/fields-alignment.md
      - Avoiding Interface Boxing: 01-common-patterns/interface-boxing.md
      - Zero-Copy Techniques: 01-common-patterns/zero-copy.md
      - Memory Efficiency and Go’s Garbage Collector: 01-common-patterns/gc.md
      - Stack Allocations and Escape Analysis: 01-common-patterns/stack-alloc.md
    - Concurrency and Synchronization:
      - Goroutine Worker Pools: 01-common-patterns/worker-pool.md
      - Atomic Operations and Synchronization Primitives: 01-common-patterns/atomic-ops.md
      - Lazy Initialization: 01-common-patterns/lazy-init.md
      - Immutable Data Sharing: 01-common-patterns/immutable-data.md
      - Efficient Context Management: 01-common-patterns/context.md
    - I/O Optimization and Throughput:
      - Efficient Buffering: 01-common-patterns/buffered-io.md
      - Batching Operations: 01-common-patterns/batching-ops.md
    - Compiler-Level Optimization and Tuning:
      - Leveraging Compiler Optimization Flags: 01-common-patterns/comp-flags.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - blog
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - include-markdown
  - rss:
      match_path: "(blog|01-common-patterns|02-networking)/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
